[package]
name = "aoc_2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino = "1.1.1"
id_tree = "1.8.0"
itertools = "0.10.5"
nom = "7"
regex = "1"
