[package]
name = "aoc_2022"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
camino = "1.1.1"
id_tree = "1.8.0"
itertools = "0.10.5"
nom = "7"
regex = "1"
svg = "0.13.0"
wasm-bindgen = "0.2"
web-sys = { version = "0.3.60", features = ['console'] }